spring:
  profiles:
    default: dev
    active: dev

# Logging
logging:
  level:
    org.springframework: ERROR
    com.bank: DEBUG
  file: "app.log"
  pattern:
    file: "%d %p %c{1.} [%t] %m%n"
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"

endpoints:


# Oracle settings
#spring.jpa.hibernate.ddl-auto=none
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/orcl
#spring.datasource.username=hr
#spring.datasource.password=oracle
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
